name: spacecraftpose
channels:
  - conda-forge
  - pytorch
dependencies:
  - albumentations=1.3.1
  - fastai=2.7.14
  - imageio=2.33.1
  - keras=2.15.0
  - lightgbm=4.3.0
  - loguru=0.7.2
  - numba=0.59.0
  - numpy=1.26.4
  - pandas=2.2.0
  - pillow=10.2.0
  - pip=24.0
  - pyarrow=15.0.0
  - pydantic=2.6.1
  - opencv=4.9.0
  - openvino=2023.2.0
  - pytest=8.0.0
  - python=3.11.7
  - pytorch-cpu=2.1.0
  - pytorch-lightning=2.1.3
  - scikit-image=0.22.0
  - scikit-learn=1.4.0
  - scipy=1.12.0
  - statsmodels=0.14.1
  - tensorflow=2.15.0
  - dill=0.3.5.1
  - torchvision=0.16.1
  - ultralytics=8.1.11
  - tqdm=4.66.2
  - xgboost=2.0.3
